#!/bin/bash
#
#Kas on algarv või mitte
#
echo -e "Sisesta suvaline arv: \c" #küsib kasutaja käest arvu
read arv #salvestab väärtuse
if [ $arv -eq 0 -o $arv -eq 1 ] # Kontrollib kas arv võrdub 1 või 0-ga
then
	echo "$arv - ei ole algarv" # väljastab vastuse
else
	jagaja=2 #jagaja väärtus
	jaak=$(($arv % $jagaja)) # #jaagi arvutamine
	while [ $jaak -ne 0 ] #kui jääk ei võrdu 0-ga
	do
		jagaja=$(($jagaja + 1)) #liidab 1 jagajale juurde
		jaak=$(($arv % $jagaja)) #jaagi leidmine
	done
	if [ $arv -eq $jagaja ] #kui arv on võrdne jagajaga
	then
		echo "$arv - on algarv" #väljastab tulemuse
	else
		echo "$arv - ei ole algarv" #väljastab tulemuse
	fi
fi
#
#skriptilopp
