#!/bin/bash
# Joonistab kujundi kasutaja sisestatud tärnide ja ridade arvuga
#
read -p "Sisesta ridade arv " rida 
read -p "Sisesta tärnide arv " arv
for (( i = 1; i <= rida; i++ )) #määrab ridade arvu ülesandes
do
echo -n $i". "
	for (( j = 1 ; j <= arv; j++ )) #määrab tärnide arvu real
	do
		echo -n "*" #väljastab tärne reavahetuseta
	done
echo "" #reavahetuseks
done
#
#skripti lõpp
