#!/bin/bash
# Joonistab kujundi kasutaja sisestatud ridade arvuga
#
read -p "Sisesta ridade arv " rida 
for (( i = 1; i <= rida; i++ )) #määrab ridade arvu ülesandes
do
echo -n $i". " #lisab numbri ridade ette"
	for (( j = rida ; j >= i; j-- )) #määrab tärnide arvu real, alustab ridade arvust ja lahutab 1 kuni 0ni 
	do
		echo -n "*" #väljastab tärne reavahetuseta
	done
echo "" #reavahetuseks
done
#
#skripti lõpp
